.coveragerc
.gitignore
.travis.yml
Makefile
Tests/__init__.py
Tests/t_untested_mods.py
tox.ini

Add coverage reporting

---

.travis.yml
Makefile
setup.py
tox.ini

Add GCOV / LCOV C coverage support

---

Lib/slapdtest.py
Tests/t_cext.py
Tests/t_ldap_sasl.py

Add test case for SASL EXTERNAL auth

---

.github/ISSUE_TEMPLATE.md
.gitignore
CONTRIBUTING.rst
Doc/.gitignore
Doc/contributing.rst
Doc/faq.rst
Doc/index.rst
Doc/installing.rst
Doc/spelling_wordlist.txt
INSTALL

Some documentation on how to contribute and maintain python-ldap.
Incidentally, this
Fixes: https://github.com/python-ldap/python-ldap/issues/50

Doc fixes & contributing guide

---

Lib/ldap/schema/subentry.py
Tests/t_ldap_schema_subentry.py

Fix schema urlfetch and add tests

---

CHANGES
Modules/ldapcontrol.c

Closes: https://github.com/python-ldap/python-ldap/issues/22

Fix error handling of LDAPControl_to_List()

---

CHANGES
Doc/reference/ldap.rst
Modules/options.c
Tests/__init__.py
Tests/t_ldap_options.py

Also adds a bunch of tests for options.

Fix set_option() of timeout to handle -1 as infinity

---

Tests/t_cext.py

OpenSSL 1.0, 1.1, and NSS return different error messages for untrusted
certificate and missing CA.
Closes: https://github.com/python-ldap/python-ldap/issues/87

Accept more error messages in test_tls_ext_noca

---

CHANGES
Doc/contributing.rst
Doc/spelling_wordlist.txt
Makefile
Misc/python-ldap.supp

Add valgrind target to check for memory leaks

---

Doc/installing.rst

Also updates build devs for Fedora and Debian.
See: https://github.com/pyldap/pyldap/issues/91#issuecomment-350098897

Provide build deps for Alpine and CentOS

---

CHANGES
Lib/ldap/pkginfo.py
Lib/ldapurl.py
Lib/ldif.py
Lib/slapdtest/__init__.py

The CHANGES include #115, which I intend to merge before release.

Release 3.0.0b1

---

Lib/ldap/constants.py
Lib/slapdtest/_slapdtest.py

More / fixed pragma: no cover

---

Tests/t_ldapobject.py

The new test case simply creates 10 connections and calls start_tls_s()
after OPT_X_TLS_NEWCTX.
See: https://github.com/python-ldap/python-ldap/issues/60

Add reproducer for NSS callback issue

---

Lib/ldap/modlist.py

Call str.lower() as a method

---

Lib/ldif.py

The current documentation of this attribute was not displayed on the online doc.

Document all_records attribute of class LDIFRecordList

---

Tests/t_ldap_syncrepl.py

Refactor syncrepl tests to run with bytes_mode

---

Lib/ldap/controls/deref.py
Lib/ldap/filter.py
Lib/ldap/functions.py
Lib/ldap/modlist.py
Lib/ldapurl.py

Updates style to modern Python idioms.

Update uses of map() to use list/set comprehensions instead

---

Doc/reference/ldap.rst
Lib/ldap/ldapobject.py
Lib/ldap/schema/models.py
Tests/t_ldapobject.py

See https://github.com/python-ldap/python-ldap/issues/147

More bytesmode

---

Tests/t_ldap_syncrepl.py

Closes: https://github.com/python-ldap/python-ldap/issues/147

Remove filterstr workaround from syncrpl test

---

CHANGES
Lib/ldap/pkginfo.py
Lib/ldapurl.py
Lib/ldif.py
Lib/slapdtest/__init__.py

See https://github.com/python-ldap/python-ldap/issues/167

Add changelog and bump version to 3.0.0

---

.indent.pro
Doc/contributing.rst
Makefile

Travis CI is picking up the wrong commit in #2. Let's see if this goes through.
See discussion in #2.

Add indent and autopep8 infrastructure (duplicate of #2)

---

Lib/slapdtest/_slapdtest.py

Disable SASL external when missing SASL support

---

Tests/t_ldapobject.py

Correct attr value's type to bytes in tests

---

Doc/faq.rst

Update FAQ to include Samba AD-DC error message

---

Lib/ldap/__init__.py

Fixes https://github.com/python-ldap/python-ldap/issues/289.

Fix thread support check for Python 3

---

Modules/functions.c
Modules/ldapcontrol.c
Modules/options.c

ldap.set_option() and ldap.get_option() now properly release the GIL
around potentially blocking calls.
Also fixes a problem with make indent by replacing
Py_BEGIN/END_ALLOW_THREADS with macros that are terminated by a
semicolon.
Fixes: https://github.com/python-ldap/python-ldap/issues/85

Release GIL around global get/set option call

---

Doc/reference/ldap.rst
Modules/LDAPObject.c
Modules/constants.c
Modules/constants.h
Modules/functions.c
Modules/ldapcontrol.c
Modules/message.c
Tests/t_cext.py
Tests/t_ldapobject.py

Work to improve how we raise exceptions on result, deals with controls and msgid being missing (#177, #208).
Ready for merging (pending #282, #283, #284 have been accepted) apart from last commit which is mainly here for initial review and can be split into its own PR if you want.

Additional exception fields

---

Doc/reference/ldap.rst
Doc/spelling_wordlist.txt
Lib/ldap/constants.py
Makefile
Modules/constants_generated.h

See: https://github.com/python-ldap/python-ldap/issues/55

Improve TLS documentation

---

Doc/reference/ldap.rst
Lib/ldap/extop/__init__.py
Lib/ldap/extop/passwd.py
Lib/ldap/ldapobject.py
Tests/t_ldapobject.py

Care has been taken to preserve backwards compatibility for the regular case of no password being requested too.

Extract new password in passwd_s (#246)

---

Modules/message.c

The function LDAPmessage_to_python() had some potential NULL pointer
derefs and missed a couple of errors checks. It's still not perfect but
a bit better now.

Fix NULL deref and checks in LDAPmessage_to_python

---

Modules/constants.c
Modules/functions.c

Make indent again

---

Doc/contributing.rst

- Git tags should be signed
- Need to check python-ldap.org

Adjust notes for the release process

---

Lib/slapdtest/_slapdtest.py

Show stderr of slapd -Ttest

---

Doc/reference/slapdtest.rst
Doc/spelling_wordlist.txt

Mention pytest-ldap in the documentation

---

LICENCE.MIT

3 people since: https://github.com/python-ldap/python-ldap/pull/417#issuecomment-877068554

Add another batch of names to LICENCE.MIT

---

Lib/ldap/controls/simple.py

Update BooleanControl encoding/decoding to use pyasn1

---

Doc/faq.rst
Doc/spelling_wordlist.txt

Hopefully some people read the FAQ.

Mention TLS gotcha in the FAQ

---

Lib/ldap/schema/models.py

I'm guessing this is partly due to commit
2be2c6bb8f44792d506cb1759fe06ff4cda3c5cf
And the update() method can't ever have worked?

ldap.schema.models.Entry - Fix init()

---

Doc/reference/ldap.rst
setup.cfg

Some detection whether we need to use -lldap_r to get threadsafe libldap

---

Lib/ldap/ldapobject.py

Make 'method' parameter of ReconnectLDAPObject._store_last_bind private

---

Doc/reference/ldap.rst

Document OPT_X_SASL_* differ from others

---

Doc/reference/ldap.rst
Lib/ldap/constants.py
Modules/constants_generated.h

Back out the removal of OPT_X_TLS and OPT_X_TLS_CTX options

---

Lib/ldap/ldapobject.py

There is a race condition in ReconnectLDAPObject._apply_method_s() when
multiple threads use a shared ReconnectLDAPObject instance:
> Traceback (most recent call last):
...
>   File "ldap/ldapobject.py", line 1259, in search_ext_s
>     return self._apply_method_s(SimpleLDAPObject.search_ext_s,*args,**kwargs)
>   File "ldap/ldapobject.py", line 1201, in _apply_method_s
>     self.reconnect(self._uri,retry_max=self._retry_max,retry_delay=self._retry_delay)
>   File "ldap/ldapobject.py", line 1181, in reconnect
>     SimpleLDAPObject.unbind_s(self)
>   File "ldap/ldapobject.py", line 905, in unbind_s
>     return self.unbind_ext_s(None,None)
>   File "ldap/ldapobject.py", line 889, in unbind_ext_s
>     msgid = self.unbind_ext(serverctrls,clientctrls)
>   File "ldap/ldapobject.py", line …

fix(ReconnectLDAPObject): reconnect race condition

---

.github/workflows/tox-fedora.yml

We're going to remove the old branch soon.

Switch tox-github-action from master to main branch

---

Doc/resources.rst

Update article links in resources.rst

---

.github/workflows/ci.yml
.github/workflows/tox-fedora.yml
Modules/options.c
setup.py
tox.ini

- Add 3.12 to setup.cfg, tox, and GHA
- Use Ubuntu 22.04 except for Python 3.6
- Add weekly cronjob to run CI

Test with Python 3.12

---

Doc/reference/ldap.rst
Lib/ldap/ldapobject.py

docs(ldapobject): fix typos in docstring
