Lib/slapdtest.py, Tests/t_bind.py
Integration tests depend on openldap client and server binaries. Fail
with a human readable message in case a tool or schema is missing.
=> Check for LDAP schema and slapd binaries

README
* Add a blank line before the list, so ReST treats it as a list
* Remove e-mail addresses
* Just make it UTF-8 and wait if someone complains – I munged Miro's name in an effort to keep it ASCII, but forgot an `ö` and others...
* Workaround for an initial
=> Format the README

Lib/ldap/controls/pagedresults.py, Modules/ldapcontrol.c, Tests/__init__.py, Tests/t_ldap_controls_libldap.py, Tests/t_untested_mods.py
The RFC 2696 function decode_page_control() had a conversion error.
`count` is an unsigned long. The correct format character for
Py_BuildValue() is 'k', not 'l'. The problem caused the function to to return
wrong value every now and then. I have seen 140728898420741 or
140728898420741 instead of 5.
Add tests for all four uncovered helper functions.
=> Fix type conversion in decode_page_control

requirements.txt, setup.py, tox.ini
pip install python-ldap will now automatically install requirements and
ensure correct versions. requirements.txt is no longer needed.
=> Move install_requires into setup.py

Makefile
With -delete, the matches must be grouped. Otherwise -delete is only
executed for the last matcher.
=> Fix syntax of find -delete

Lib/ldap/schema/subentry.py
Alternate version of #25 that avoids `eval()` entirely.
Issue for a more proper fix filed here: https://github.com/python-ldap/python-ldap/issues/34
Fixes: https://github.com/python-ldap/python-ldap/pull/25
=> Lib: Avoid eval() for getting module-level variables

Modules/LDAPObject.c, Tests/t_cext.py
On several occasions LDAPObject methods did not clean up LDAPControls
and other resources when LDAPControls_from_object() fails. This bug
would lead to memory leaks in case a server control or client control
could not be handled correctly.
Closes: #18
This was originally PR #21, see comment https://github.com/python-ldap/python-ldap/pull/21#issuecomment-347233773
=> Fix resource leaks in error cases

INSTALL, Lib/slapdtest.py, Tests/t_cext.py, Tests/t_edit.py
Add documentation how to run refleak tests with pydebug build of
CPython and pytest-refleak. Refleak testing runs each unit test multiple
times. Some small changes are required to clean up after each test cycle
and to avoid extra references.
* Only create logging structure for SlapdObject once. The logging
framework creates reference cycles that cause false positives.
* Clean up and remove atexit handlers in SlapdObject.stop()
* Remove new entries at the end of each test, either with an
explicit delete_s() or an write area, which is removed in tearDown().
=> C extension reference leak testing

Makefile
Scan-build is a frontend to clang's static code analyzer. It checks C
code for bugs.
=> Add make target for scan-build

Modules/LDAPObject.c
Two error cases are missing a Py_XDECREF(valuestr). A password change
with an invalid old password triggers a reference leak.
Closes: #37
=> Fix reference leak in passwd()

Lib/slapdtest.py
slaptests use SysLogHandler() to write logs to syslog. Don't create a
SysLogHandler when /dev/log does not exist. This fixes a bug when
building and testing python-ldap in containers or restricted build
environments.
=> Omit SysLogHandler when /dev/log does not exist

Modules/LDAPObject.c, Modules/ldapmodule.c
PyType_Ready() takes care of the base type for us. Also check PyType_Ready()
result for error.
=> Use standard PyVarObject_HEAD_INIT() call

Modules/LDAPObject.c, setup.cfg
Compilers' and linkers' default search paths are fine on modern Linux. The
custom search path was wrong on 32bit platforms anyway. When library_dirs is
defined, distutils also adds rpath to the shared library. An rpath
should not be added by default.
I only commented out the configuration stanzes to keep them as example.
Closes: https://github.com/python-ldap/python-ldap/issues/30
=> Don't define search path for includes and libs

.travis.yml, Modules/LDAPObject.c, Modules/ldapcontrol.c, Modules/ldapmodule.c
* Correct return LDAPerror_TypeError(). LDAPerror_TypeError() returns ``(PyObject *)NULL``. Some functions don't return a ``PyObject*`` so technically it's wrong to return ``(PyObject *)NULL``. Return NULL instead.
* Fix implicit declaration of error functions, ldapcontrol.c was missing include of constants.h that defines LDAPerr() and LDAPerror().
* Make init_ldap_module definition a strict prototype
* Travis: Turn compiler warnings into fatal errors
=> Fix several compiler warnings and make warnings fatal errors

.travis.yml, Modules/LDAPObject.c, Modules/constants.c, Modules/ldapmodule.c, Modules/message.c
In strict ISO C90 mode and on some platforms (e.g. older MSVC), it is
not allowed to declare new variables after a statement. I also find it
good practice to declare first.
Fixes error: ISO C90 forbids mixed declarations and code
[-Werror=declaration-after-statement]
=> Fix declaration after statement for C90

Tests/t_ldap_sasl.py
On Fedora 27, test_external_tlscert fails with CONNECT_ERROR when the
test case is executed with the rest of the suit. It works fine when
executed on its own.
Skip the test on error for now until I have time to investigate.
=> Skip cert auth test when start_tls fails

Tests/t_bind.py, Tests/t_edit.py
Both test modules used to set up their own server instance. t_edit
didn't clean up properly. Let's use SlapdTestCase test class everywhere.
=> Use SlapdTestCase in t_bind and t_edit

CHANGES, Doc/bytes_mode.rst, Doc/index.rst, Doc/reference/ldap.rst, Lib/ldap/functions.py
This moves the bytes_comment from the main page of the docs.
=> Doc: Add dedicated page for bytes_mode

.travis.yml, Lib/slapdtest.py, Tests/t_cext.py, Tests/t_ldap_sasl.py
Some TLS tests are broken or flaky when libldap is compiled with NSS as
TLS provider. It currently affects Fedora 27 and older releases.
Fedora issue: https://bugzilla.redhat.com/show_bug.cgi?id=1519167
https://github.com/python-ldap/python-ldap/issues/60
=> Skip some TLS tests when libldap used NSS

MANIFEST.in
PKG-INFO is generated by setup.py.
There's only one licence file, in the root.
=> Infra: Remove nonexistent files from MANIFEST.in

Doc/installing.rst
This rendered as follows:
> OpenLDAP client libs version 2.4.11 or later It is not possible and not supported to build with prior versions.
=> Doc: Add a separator between sentences

MANIFEST.in
Source distributions (sdist) of python-ldap now contain documentation.
This allows users to build and read docs locally. Also fixes tox test
run in sdist.
=> Ship documentation in source distribution

CHANGES, Modules/LDAPObject.c
l_ldap_whoami_s() did not free the berval struct from ldap_whoami_s().
Closes: https://github.com/python-ldap/python-ldap/issues/80
=> Fix memory leak in whoami_s

CHANGES, Modules/ldapcontrol.c
encode_assertion_control was leaking a LDAP* struct and BER data values
on every call. Both data structures are now properly freed and the GIL
is released around ldap_create() and ldap_unbind_s().
Closes: https://github.com/python-ldap/python-ldap/issues/79
=> Fix two memory leaks in encode_assertion_control

.travis.yml, Doc/contributing.rst, Lib/slapdtest/__init__.py, Lib/slapdtest/_slapdtest.py, Tests/t_cext.py, Tests/t_ldap_sasl.py, Tests/t_ldapobject.py, tox.ini
Also fixes tests when _ldap extension is compiled without SASL support.
=> Run tests without SASL and TLS bindings

Demo/pyasn1/sessiontrack.py, Demo/pyasn1/syncrepl.py, Demo/simplebrowse.py
Demo scripts used different style of shebangs. The shebang
"#!/usr/bin/env python" is preferred because it works nicely in virtual
envs.
=> Use uniform shebang in all demos

CHANGES, Doc/contributing.rst
Well, 3.0.0b1 is tagged, but – of course I forgot something.
That's why I'm doing a beta.
=> Add the 3.0.0b1 release date to CHANGES

Modules/LDAPObject.c, Tests/t_ldap_options.py
The method LDAPObject.set_option() did not signal an exception in case
the set option failed. The bug was caused by checking for the wrong
error value. The internal C function LDAP_set_option() returns ``1`` for
sucess and ``0`` for error, but LDAPObject.set_option() was checking for
``-1``.
Add some tests for LDAPObject.set_option() and LDAPObject.get_option().
Closes: https://github.com/python-ldap/python-ldap/issues/100
=> Fix error reporting of LDAPObject.set_option()

Doc/installing.rst, Lib/slapdtest/_slapdtest.py, Tests/t_cext.py, Tests/t_ldap_sasl.py
The NSS issue has been fixed in Fedora update openldap-2.4.45-2.fc26 and
openldap-2.4.45-4.fc27. Fedora users can now execute all tests.
Includes documentation for build requirements and minimum versions on
Fedora.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1520990
Closes: https://github.com/python-ldap/python-ldap/issues/60
Closes: https://github.com/python-ldap/python-ldap/issues/51
=> Remove workaround for OpenLDAP NSS issue

Doc/bytes_mode.rst, Doc/reference/ldap.rst, Lib/ldap/__init__.py, Lib/ldap/ldapobject.py, Tests/t_ldapobject.py
Under Python 2, python-ldap now uses custom ldap.LDAPBytesWarning
instead of BytesWarning to emit warnings in default bytes mode.
Closes: https://github.com/python-ldap/python-ldap/issues/99
=> Use custom ldap.LDAPBytesWarning class

Doc/reference/ldap.rst, Modules/options.c, Tests/t_ldap_options.py
The setter for network timeout and timeout options now support None as
value. None is mapped to infinity.
Closes: https://github.com/python-ldap/python-ldap/issues/95
=> Support None for set_option(OPT_NETWORK_TIMEOUT)

.travis.yml, Modules/LDAPObject.c
attrs_from_List() no longer uses internal buffers of bytes/str PyObject*
to maintain memory. Instead it creates its own copies, which are then
passed to ldap_search_ext() and then cleaned up.
The modification is required for Python 3.7. PyUnicode_AsUTF8() returns
const char* but ldap_search_ext() does not use const.
Closes: https://github.com/python-ldap/python-ldap/issues/105
=> Change memory handling in attrs_from_List()

Makefile, Misc/python-ldap.supp
* make valgrind now fails when valgrind detects a definitive memory leak
* suppress a known memory leak in OpenLDAP's NSS module
* suppress some extra noise from CPython
=> Make valgrind check more useful

Doc/contributing.rst, Doc/sample_workflow.rst
The Contributing docs were too long to read.
Move the longness out, which should emphasize you'll be fine with the usual Git workflows.
=> Doc: Move sample workflow out of the main document

Demo/pyasn1/syncrepl.py, Lib/ldap/asyncsearch.py, Lib/ldap/controls/deref.py, Lib/ldap/controls/psearch.py, Lib/ldap/ldapobject.py, Lib/ldap/schema/models.py, Lib/ldap/syncrepl.py, Lib/ldif.py, Tests/t_ldap_syncrepl.py, setup.py
- Use a dict literal instead of calling `dict()`.
- Use a list literal instead of calling `list()`.
- Use a set literal instead of calling `set()`.
- Use a tuple literal instead of calling `tuple()`.
- Use dict comprehension
These syntax expressions are available by all supported Python versions. Literals are always faster than calling the constructor. More idiomatic with wider Python community.
=> Prefer literals throughout project

setup.py
Modern Python installations contain setuptools. It is reasonable to expect it to exist. Simplifies `setup.py` and removes the large comment explaining the workaround.
=> Drop distutils workaround and simplify setup.py

.travis.yml, tox.ini
To my surprose, python-ldap works just fine with PyPy2. For Python 3,
PyPy-5.9 (Python 3.5) is required. Fedora's and Ubuntu's PyPy 5.5 is
too old (Python 3.3).
=> Run Travis tests with PyPy

tox.ini
The second full tox run fails because 'py27' target is picking up C
object files from 'py2-nosasltls'. Each target needs to clean up and
start from scratch.
=> Run clean --all in all tox targets

Doc/reference/ldap.rst, Doc/reference/ldif.rst, Lib/ldap/functions.py, Lib/ldif.py
- `ldap.open()`
- `ldif.CreateLDIF()`
- `ldif.ParseLDIF()`
=> Doc deprecated functions for removal in 3.1

Lib/slapdtest/_slapdtest.py
"pragma: no cover" was added to two helper functions in slapdtest to
avoid spurious changes in coverage whenever slapd has a hick up.
Closes: https://github.com/python-ldap/python-ldap/issues/127
=> Add pragma: no cover to avoid spurious cov changes

Lib/ldap/functions.py, Lib/ldap/ldapobject.py, Modules/ldapmodule.c, Tests/t_ldapobject.py
This is a simplification of https://github.com/python-ldap/python-ldap/pull/120 (and https://github.com/python-ldap/python-ldap/pull/109).
Turns out extension functions have `globals()`, and putting the marker in the `_ldap` module as well means we can only walk the stack – no other changes necessary.
BTW I do like removing `_bytesify_inputs`! Let's do that in 3.1.
I did have some trouble in py2 tests, see the `_normalize` inner function.
=> When raising LDAPBytesWarning, walk the stack to determine stacklevel

Lib/ldap/ldapobject.py
Inequalities already return return a boolean. Coercing to a bool again is a noop.
=> Remove unnecessary bool() call

Lib/ldap/cidict.py, Lib/ldap/schema/models.py
Reimplements the parent class implementation. Can simplify classes by removing it.
=> Remove override of UserDict.get() to avoid reimplementation

Lib/ldap/ldapobject.py, Tests/t_ldapobject.py
Based on earlier patch by Christian Heimes
Fixes: https://github.com/python-ldap/python-ldap/issues/132
Fixes: https://github.com/python-ldap/python-ldap/issues/144
=> Show argument name instead of content in LDAPBytesWarning

Lib/ldap/compat.py, Lib/slapdtest/__init__.py, Lib/slapdtest/_slapdtest.py, Tests/t_ldap_sasl.py, Tests/t_ldap_schema_subentry.py, Tests/t_ldapobject.py, tox.ini
A bunch of small chances to the test suite. It should be enough to make it possible to run the test suite under macOS homebrew and Windows (untested).
* Make LDAPI optional
* Drop unused import of pwd module
* Lookup test binaries in PATH
=> Make testing on non-Linux platforms easier

CHANGES, Lib/ldap/pkginfo.py, Lib/ldapurl.py, Lib/ldif.py, Lib/slapdtest/__init__.py
I'd rather release 3.0.0 already, and drop the betas. But, there are two reasons this is not a good time:
* python-ldap.org is down (see mailing list)
* people are taking vacations before the end of year; doing a release now might not be convenient
On the other hand, I want to open the door to 3.1 changes, which have been piling up.
So, I'm thinking about creating a 3.0 branch after 3.0.0b3 is released, and start merging 3.1 changes to master.
=> Prepare release 3.0.0b3

.travis.yml, Doc/installing.rst, setup.py, tox.ini
Python 3.3 is end of life. It is no longer receiving bug fixes including
for security issues. It has been EOL since 2017-09-29. For a library
focused on authentication, supporting environments that are not
receiving security sends the wrong message. For additional details, see:
https://devguide.python.org/#status-of-python-branches
Reduces testing and maintenance resources.
=> Remove support for EOL Python 3.3

Doc/reference/ldap.rst, Lib/ldap/ldapobject.py, Modules/LDAPObject.c, Tests/t_ldapobject.py
sasl_bind_s() has accepted None for who and cred for a long time. Now
simple_bind() and simple_bind_s() default to and accept None, too.
See: https://github.com/python-ldap/python-ldap/issues/147
=> simple_bind() accept None for who and cred

Misc/python-ldap.supp
libldap's NSS engine has one known memory leak. One block of memory is
leaked one time only. The existing rule only matches when all debug
symbols are installed. The new rule should work without debug symbols.
Closes: https://github.com/python-ldap/python-ldap/issues/156
=> Improve valgrind rule for PR_strdup

Modules/ldapcontrol.c
ber_scanf() and ber_printf() "i" format uses ber_int_t. lber_types.h
defines the type as int but Python code assumes the type to be unsigned
long:
```
#define LBER_INT_T int
typedef LBER_INT_T ber_int_t;
```
The code was working fine on little endian machines but broke on big
endian machines. ber_int_t is now correctly parsed as signed int.
Fixes: https://github.com/python-ldap/python-ldap/issues/161
=> Use correct types for BER en/decode

Tests/t_ldapobject.py
Closes: https://github.com/python-ldap/python-ldap/issues/160
=> Ignore SASL methods in DSE test

Lib/ldap/ldapobject.py, Modules/LDAPObject.c, Modules/functions.c, Modules/ldapcontrol.c, Tests/t_cext.py, Tests/t_ldapobject.py
It's a bit hard to understand where the TypeError excactly comes from.
The exception now contains the argument name.
=> Make bytes mode TypeError more useful

setup.cfg
setup.cfg overrides settings in setup.py. Include lber in list of
libraries in setup.cfg, too.
=> Link with lber

Doc/bytes_mode.rst, Doc/reference/ldap.rst, Lib/ldap/ldapobject.py, Tests/t_ldapobject.py
See https://github.com/python-ldap/python-ldap/issues/166 for initial discussion, or the changed docs for what is added.
I've used `bytes_strictness` instead of `bytes_warnings`, since warnings is just one of the possible behaviors. The new name isn't perfect either, though.
=> Add bytes_strictness to allow configuring behavior on bytes/text mismatch

Doc/installing.rst
3.0.0 final is out so the instructions should apply for `pip install`.
=> Doc: Remove warning about unreleased version

.travis.yml, Lib/ldap/__init__.py, Lib/ldap/ldapobject.py, Tests/t_ldapobject.py, tox.ini
python-ldap can trace LDAP calls, but it was not possible to use the
feature without changing code manually. Tracing can now be enabled with
the env var PYTHON_LDAP_TRACE_LEVEL and redirected to a file with
PYTHON_LDAP_TRACE_FILE.
=> Add tests and coverage for tracing

.indent.pro, Doc/contributing.rst, Makefile
* indent is a tool to auto-format C code. The ``.indent.pro`` file is based on CPython's ``Misc/indent.pro`` file. It should get us very close to PEP 7 compatible C code.
* autopep8 is a Python library to auto-format Python code. It can be used to address single pycodestyle violation, e.g. ``E121 - Fix indentation to be a multiple of four.``. See https://pypi.python.org/pypi/autopep8#features
=> Add indent and autopep8 infrastructure

Doc/reference/ldap.rst, Lib/ldap/__init__.py, Lib/ldap/functions.py
The functions have been deprecated since at least the introduction of the file `Lib/ldap/functions.py` in commit e4173acd69254b950dfeb7663e83a8e338f5df18 on 2011-11-23. That has been lots of time for library users to see the warning and update calling code.
With the move to 3.0.0, a new major version, this is an opportune time to drop deprecated, unused functionality.
=> Remove long deprecated functions ldap.open() and ldap.init()

Lib/ldap/cidict.py, Lib/ldap/modlist.py, Lib/ldap/schema/models.py, Lib/ldap/schema/subentry.py, Lib/ldapurl.py, Lib/ldif.py, Tests/t_cidict.py
When reviewing #138 I found some cases where `items()` would be more appropriate than `keys()` or iterating the dict itself.
The fix for `__iter__()` from #138 is included as a separate commit.
=> Use items() when appropriate in dict iteration

Lib/slapdtest/_slapdtest.py
Looks like a simple mistake. Introduced in 2ce408cf8b7d5b084556de0d36bf5666c1fda515.
=> Remove assignment of variable to itself

tox.ini
Python 3.4 is in its security fix only phase. We should make sure
the tests pass, but warnings should no longer break CI.
=> Tests: Disable warnings-as-errors for Python 3.4

Lib/ldap/controls/ppolicy.py, Tests/t_ldap_controls_ppolicy.py
Password policy control decoder failed to handle graceAuthNsRemaining
correctly. The warning.getComponentByName('timeBeforeExpiration') call
materialized the time before expiration CHOICE element. The fixed
implementation uses pyasn1's dict interface to check which CHOICE
element is set.
Closes: https://github.com/python-ldap/python-ldap/issues/192
See: https://github.com/python-ldap/python-ldap/issues/193
=> Fix parsing of PPolicyControl ASN.1 structure

Lib/slapdtest/_slapdtest.py
Allows overriding `SlapdObject.suffix` or `SlapdObject.root_cn` without also requiring `root_dn` be defined. It is now computed from the existing values at runtime. The result is an easier to use `SlapdObject` class.
=> Make SlapdObject.root_dn a property

Lib/slapdtest/_slapdtest.py
Allows overriding openldap_schema_files without requiring rewriting the conf file.
=> In SlapdObject,  build include directives dynamically

Lib/slapdtest/_slapdtest.py, Tests/t_slapdobject.py
Allows for automatic cleanup of resources using the with statement. For example:
```py
with slapdtest.SlapdObject() as server:
server.ldapadd(...)
...
```
When using `SlapdObject` in a function, it is more convenient and concise than using a `try`/`finally` pattern.
=> Make SlapdObject a context manager

.gitignore
Starting with Pytest 3.4.0 (2018-01-30), Pytest's cache directory was renamed to `.pytest_cache`.
https://docs.pytest.org/en/latest/changelog.html#pytest-3-4-0-2018-01-30
> The default cache directory has been renamed from `.cache` to `.pytest_cache` after community feedback that the name `.cache` did not make it clear that it was used by pytest.
=> Update Pytest cache directory in gitignore

Lib/ldap/asyncsearch.py, Lib/ldap/schema/subentry.py
For import statements that can safely exist at the top level of the file, move them there.
In `Lib/slapdtest/_slapdtest.py`, having imports local to functions unnecessarily resulted in duplicates.
This style is also more in line with PEP8:
https://www.python.org/dev/peps/pep-0008/#imports
> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.
=> Move import statements to top level

Demo/pyasn1/README, Doc/contributing.rst, Doc/faq.rst, Doc/installing.rst, setup.py
For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html
=> Update all pypi.python.org URLs to pypi.org

Tests/t_cext.py
Fix a pattern where `assertTrue(result, _ldap.RES_BIND)` was mistakenly used in place of `self.assertEqual(result, _ldap.RES_BIND)`.
Mistakes introduced in commit 162cedf71ba62b3944d18a27ed206d55e679f966.
=> Fix assertTrue(result, _ldap.RES_BIND) to assertEqual()

Tests/t_cext.py, Tests/t_cidict.py, Tests/t_ldap_options.py, Tests/t_ldapurl.py
These methods were introduced in Python 2.7 and 3.1. Available in all supported environments. Can remove the local reimplementation.
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertIsNone
https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertIsNone
=> Use builtin unittest methods assertIsNone & assertIsNotNone

Modules/message.c
PyDict_GetItem() returns a borrowed reference. The code later
Py_DECREF() the reference, which causes a segfault at a later point in
time.
Fixes: https://github.com/python-ldap/python-ldap/issues/218
=> Fix ref counting bug in LDAPmessage_to_python

Tests/t_ldap_modlist.py
The `modlists` variable in the code below is an return value of `ldap.modlist.addModlist()` expected by the tests in Tests/t_ldap_modlist.py, exactly extracted from the `test_addmodlist` case in the file (https://github.com/python-ldap/python-ldap/blob/master/Tests/t_ldap_modlist.py#L22-L29 ).
`add_ext_s()` with it raises `TypeError` on Python 3 though (Traceback is below).
This PR fixes tests in Tests/t_ldap_modlist.py .
Code:
```python
#!/usr/bin/env python3
import ldap
import ldap.modlist
URI = "ldaps://localhost:1636"
ADMIN_DN = "cn=admin,dc=example,dc=com"
ADMIN_PASSWORD = "secret"
def ldap_add_string_list(lo, dn):
modlists = [
('objectClass',['person','pilotPerson']),
('cn',['Michael Str\303\266der','Michael Stroeder']),
('sn',['Str\303\266der']),
('dummy2',['2']),
('dummy3',['']), …
```
=> byte/text expectation in ldap.modlist test cases were obsolete in Python 3

CHANGES, Doc/reference/ldap.rst, Lib/ldap/ldapobject.py, Tests/t_ldapobject.py
Previously, `LDAPObject.compare_s()` and `LDAPObject.compare_ext_s()` returned 1 for true and 0 for false. As the return value is intended for a `bool` context, return a `bool` instead.
=> Return a bool in .compare_s() and .compare_ext_s()

Doc/reference/ldap.rst
Previous syntax did not create links and appeared as raw rst syntax.
https://www.python-ldap.org/en/python-ldap-3.0.0/reference/ldap.html#options
=> Docs: Fix internal set|get_option func|meth references

Tests/t_cext.py, Tests/t_ldapobject.py
The integer values for `errno` are  not standard and can vary from
platform to platform, so the tests should rely on the constants
provided in `errno` module.
Closes: #228
=> tests: Use system-specific ENOTCONN value

.travis.yml, tox.ini
Let's catch issues early – both in python-ldap and CPython.
With all relevant compilers supporting C99, Python 3.6+ makes use of [some C99 features](https://www.python.org/dev/peps/pep-0007/#c-dialect), and in 3.8-dev `//` comments found their way to headers included from `Python.h`.
I'd like to keep checking C90 compat for older Python versions, hence a bit of indirection to set the -std flag.
=> Add Python 3.8-dev to Tox config

Doc/bytes_mode.rst, Doc/conf.py, Doc/installing.rst, Doc/sample_workflow.rst
The intersphinx extension can generate automatic links to the documentation of objects in other projects. For complete details on intersphinx, see:
http://www.sphinx-doc.org/en/master/ext/intersphinx.html
=> In docs, use intersphinx to link to Python documentation

Lib/ldap/schema/models.py, Tests/t_ldap_schema_subentry.py
389 Directory Server uses X-ORIGIN ObjectClass attribute for determining if the ObjectClass is 'user defined' or not. 389 Directory Server UI currently depends on it.
Also, X-ORIGIN is already supported for AttributeType schema element. So it makes sense to make it consistent across these two schema elements.
=> Add support for X-ORIGIN in schema element class ObjectClass

Doc/reference/ldap.rst, Lib/ldap/functions.py, Lib/ldap/ldapobject.py
Fixes: #249 
Also, documentation for these should now match the code.
=>  Make initialize() pass extra keyword arguments to LDAPObject 

Lib/ldap/controls/sss.py, Tests/t_ldap_controls_sss.py
=> Python 3 has no basestring, use str instead

Doc/requirements.txt
The documentation build uses docstrings from the code, and so it needs the code to be importable.
We already use a fake _ldap module for cases where the C compiler is not available, like on Read the Docs.
Another issue on Read the Docs is that the `pyasn1` dependency needs to be installed. This can't be done automatically via setup.py install, as that would attempt to build C code.
Instead, add a documentation-only "requirements.txt", which we can point Read the Docs to.
=> Add Doc/requirements.txt for Read the Docs build

Lib/ldap/__init__.py
All use of these attributes *should* be guarded by `if __debug__`.
However, that's not always the case. Providing different API based
on `__debug__` is unnecessarily fragile.
This is intended as a quick fix for a maintenance release (3.1.1). More coming up in another PR.
Fixes: https://github.com/python-ldap/python-ldap/issues/226
=> Lib/ldap: Provide _trace_level and _trace_file in non-debug mode

CHANGES, Lib/ldap/pkginfo.py, Lib/ldapurl.py, Lib/ldif.py, Lib/slapdtest/__init__.py
With https://github.com/python-ldap/python-ldap/issues/226 fixed, it makes sense to do release.
We have a new feature, X-ORIGIN support, so the release should be 3.2.0.
=> Update the changelog and release 3.2.0

Doc/reference/ldap.rst, Lib/ldap/ldapobject.py, Tests/t_ldapobject.py
Pass ``(ldap_res,)`` tuple to string formatting instead of ``ldap_res``.
This changes fixes ``TypeError: not all arguments converted during string
formatting``.
Fixes: https://github.com/python-ldap/python-ldap/issues/270
compare_s() may fail with an exception in case the DN is not found or the user searches for an unspecified attribute.
=> Fix TypeError in compare_s, test and document error behavior

Lib/ldap/dn.py, Tests/t_ldap_dn.py
* Fixed escaping a single space ldap.dn.escpae_dn_chars(' ')
* Adjust the tests to include a test for every escaped character
See Issue #252
=> Fix escape dn chars

Lib/ldap/modlist.py, Lib/ldap/schema/subentry.py, Tests/t_ldap_syncrepl.py
Calling `dict.keys()` is unnecessary. `iter(dict)` is equivalent to `dict.keys()`. Inspired by Lennart Regebro's talk "Prehistoric Patterns in Python" from PyCon 2017.
https://www.youtube.com/watch?v=V5-JH23Vk0I
=> Prefer iterating dict instead of calling dict.keys()

Doc/reference/ldap.rst
Previously, the class showed up as `ldap.LDAPObject`, which is wrong.
<s>Note that the documentation on Read the Docs is currently not building (see https://github.com/python-ldap/python-ldap/pull/260). The `SimpleLDAPObject` and `ReconnectLDAPObject` entries show up fine with current master, but not on the published docs.</s>
Fixes: https://github.com/python-ldap/python-ldap/issues/256
Originally, `ldap.ldapobject.LDAPObject` was meant as a read/write alias of the "default" connection class.
However, setting module attributes is bad practice (action at distance): it affects all users of python-ldap, some of which might not be aware of each other.
Clarify that:
* `initialize()` is a thin wrapper around calling `LDAPObject()`,
* it is fine and recommnended to instantiate LDAPObject-like …
=> Doc: Clarify and improve documentation of ldap.ldapobject.LDAPObject

Modules/LDAPObject.c
There are two code paths in `l_ldap_result4` that allow serverctrls to be leaked. This plugs them.
=> Do not leak serverctrls

Lib/slapdtest/_slapdtest.py
If we point SBIN to $openldap_source/servers/slapd, libtool scripts will
munge argv[0] and slapd won't recognise it's slaptest we asked for. So
just request a slapd tool directly.
=> Use slapd -Tt instead of slaptest

Lib/ldap/ldapobject.py, Tests/t_ldapobject.py
Considering the following code:
```python
import ldap
import subprocess
bind_dn = 'uid=Administrator,cn=users,l=school,l=dev'
bind_pw = 'univention'
ldap_addr = 'ldap://localhost:7389'
lo = ldap.ldapobject.ReconnectLDAPObject(ldap_addr, retry_max=2, retry_delay=1)
lo.bind_s(bind_dn, bind_pw)
subprocess.check_call(['systemctl', 'stop', 'slapd'])
try:
_ = lo.search_s('l=school,l=dev', ldap.SCOPE_SUBTREE, '(uid=Administrator)')
except ldap.LDAPError as exc:
print('Exception raised as expected')
print(exc)
else:
assert False, 'cannot happen'
finally:
subprocess.check_call(['systemctl', 'start', 'slapd'])
print('\n######################')
print('Unexpected exception')
_ = lo.search_s('l=school,l=dev', ldap.SCOPE_SUBTREE, '(uid=Administrator)')
print(_)
```
which currently results in:
``` …
```
=> Fix reconnection handling

Lib/ldap/dn.py
Cherry-picked change from https://github.com/python-ldap/python-ldap/pull/272
=> ldap.dn.is_dn: Fix typo in docstring

setup.cfg, setup.py
Currently [pip-licenses](https://github.com/raimon49/pip-licenses) can't include the LICENSE file for this project because the correct metadata is not setup.
This PR sets up the metadata correctly so the LICENSE file is properly included/linked to in source and wheel distributions.
=> Add LICENSE file metadata to package distributions

Doc/reference/ldif.rst
Fixes: https://github.com/python-ldap/python-ldap/issues/306
=> Doc: Use bytes for attribute values in example

Doc/reference/ldap.rst
This fixes the build with newer versions of Sphinx.
(The entry is duplicated on line 444.)
=> Doc: Remove duplicate entry for NO_OBJECT_CLASS_MODS

Lib/ldap/schema/tokenizer.py, Tests/t_ldap_schema_tokenizer.py
One of the failures actually stems from using the wrong method. Extending the tokenizer to deal with escapes gets rid of the other.
=> Get rid of expected failures in tokenizer tests

Modules/LDAPObject.c
Allocate ``(strlen + 1) * sizeof(char)`` instead of
``(strlen + 1) * sizeof(char*)`` for a ``char[]`` in
``attrs_from_List()``.
=> Don't overallocate memory in attrs_from_List()

Doc/reference/ldap.rst
Fixes: https://github.com/python-ldap/python-ldap/issues/301
=> Document that TLS options are backend specific

Lib/ldap/cidict.py, Tests/t_cidict.py
The functions are undocumented, untested, unused, and can now be trivialy
implemented with set operations.
=> Deprecate cidict's strlist functions

Doc/reference/ldap.rst, Tests/t_ldapobject.py
Otherwise calling result4() can return exceptions like NO_SUCH_OBJECT or
COMPARE_TRUE without the caller being able to find the matching asynchronous
operation that failed.
This change adds the message id as an argument to the exception.
=> Store message id for exceptions raised from result4()

.coveragerc, .travis.yml, tox.ini
setup.py test is deprecated and causes issues with testing our code.
There are cases where the wrong shared library is picked up.
The ``unittest discover`` approach avoids building the extension twice.
python-ldap should move to pytest eventually.
Fixes: https://github.com/python-ldap/python-ldap/issues/326
=> Tox: replace setup.py test with unittest discover

Doc/reference/ldap.rst, Lib/ldap/functions.py, Lib/ldap/ldapobject.py, Lib/slapdtest/_slapdtest.py, Modules/LDAPObject.c, Modules/functions.c, Tests/t_cext.py, Tests/t_ldapobject.py, setup.py
``ldap.initialize()`` now takes an optional fileno argument to create an
LDAP connection from a connected socket.
set_option() and get_option() now verify that LDAPObject is valid. This
fixes an assertion error and possible segfault after unbind_ext().
=> Allow LDAP connection from file descriptor 

Lib/ldap/cidict.py, Lib/ldap/compat.py, Lib/ldapurl.py, Tests/t_cidict.py
he UserDict API is not specified when it comes to extending:
it is not clear which methods can be safely overridden.
The MutableMapping ABC fixes this problem by providing an explicit
set of abstract methods, in terms of which the rest of the API
is implemented.
=> Rewrite cidict and LDAPUrlExtensions in terms of MutableMapping

tox.ini
It looks like all the warnings were caused by setuptools.
Since we don't use setuptools in tests any more, we can remove the warnings.
=> Do not ignore warnings in tox config

.travis.yml, tox.ini
At the moment coverage is causing more trouble than it's worth. Codecov
isn't giving meaningful results and we aren't using coverage to increase
test coverage.
Fixes: https://github.com/python-ldap/python-ldap/issues/348
=> Remove coverage

Lib/ldap/syncrepl.py, Tests/t_ldap_syncrepl.py
Previously, the SyncInfoMessage parser used a for loop to test for the
presence of each named choice with with the structure. However, because
refreshDelete and refreshPresent both are able to be fully resolved
as defaults, and due to how pyasn1 accesses named types, it was not
checking the choice tag, and would return a fully populated refreshDelete
to the caller instead.
This fixes the parser to always return the inner component, and retrieves
the name based on the current choice of the tagged item.
Author: William Brown <william@blackhats.net.au>
=> Syncrepl fails to parse SyncInfoMessage when the message is a syncIdSet

Modules/LDAPObject.h, Modules/berval.h, Modules/common.h, Modules/constants.c, Modules/constants.h, Modules/functions.c, Modules/ldapcontrol.c, Modules/ldapcontrol.h, Modules/message.h, setup.py
OpenLDAP 2.4.48 added openldap.h, which defines ldap_init_fd. Use the
header file with 2.4.48 and define the function for older versions.
The patch also cleans up #include. All OpenLDAP includes are now in
common.h and use global includes ``#include <ldap.h>`` instead of local
includes ``#include "ldap.h"``.
Fixes: https://github.com/python-ldap/python-ldap/issues/353
See: https://bugs.openldap.org/show_bug.cgi?id=8671
=> Use openldap.h on OpenLDAP 2.4.48

Doc/reference/ldap.rst
Looking at the list of changfes, I realized the `LDAPError` info dict if poorly documented. This should help.
Also, this corrects the note on `COMPARE_FALSE` and `COMPARE_TRUE`, which was contradicting the `'msgid'` doc.
=> Document the LDAPError fields

.travis.yml, Doc/bytes_mode.rst, Doc/faq.rst, Doc/reference/ldap.rst, Doc/reference/ldapurl.rst, Doc/sample_workflow.rst, Lib/ldap/cidict.py, Lib/ldap/compat.py, Lib/ldap/controls/sss.py, Lib/ldap/dn.py, Lib/ldap/functions.py, Lib/ldap/ldapobject.py, Lib/ldap/schema/models.py, Lib/ldap/schema/subentry.py, Lib/ldapurl.py, Lib/ldif.py, Lib/slapdtest/_slapdtest.py, Modules/LDAPObject.h, Modules/ldapmodule.c, Tests/t_bind.py, Tests/t_cext.py, Tests/t_edit.py, Tests/t_ldap_dn.py, Tests/t_ldap_syncrepl.py, Tests/t_ldapobject.py, Tests/t_ldapurl.py, Tests/t_ldif.py, setup.py, tox.ini
python-ldap 3.4 will require Python 3.6 or newer.
=> Remove Python 2 support

Doc/spelling_wordlist.txt
it looks like sphinxcontrib-spelling 5.1.2 does not like GPG and
readthedocs.
=> Add words to spellchecker

.travis.yml
pip may point to Python 2 but setup.py requires Python 3. Tox sdist may
fail when tox is installed for Python 2 on Travis CI.
=> Force Python 3 tox on Travis CI

.travis.yml, Doc/reference/ldap.rst, Lib/ldap/constants.py, Lib/ldap/ldapobject.py, Lib/slapdtest/__init__.py, Lib/slapdtest/_slapdtest.py, Modules/common.h, Modules/constants_generated.h, Modules/functions.c, Tests/t_cext.py, Tests/t_ldapobject.py, setup.py, tox.ini
macOS system libldap 2.4.28 does not have ldap_init_fd symbol. Disable
initialize_fd when Apple libldap 2.4.28 is detected.
Also run some macOS tests on Travis CI. Since the SDK does not ship
slapd, testing is rather limited.
Fixes: https://github.com/python-ldap/python-ldap/issues/359
=> Fix macOS SDK builds without ldap_init_fd

Doc/contributing.rst, Makefile, pyproject.toml
Also removes autopep8 and prepares configuration for import sorter
isort.
=> Prepare auto-formatting with black

tox.ini
Tox can pass positional arguments to test runners. This allows for instance to debug a single test with `tox -e py38 -- -f -k test_foobar`.
=> tox positional arguments

Doc/installing.rst
Use backticks around setup.cfg as it is a filename.
This resolves a failure that occurs in sphinxcontrib.spelling due to
trying to import setup.cfg.
=> Fix CI failure on docs

Lib/ldap/cidict.py, Tests/t_cidict.py
The copy() method vanished when cidict was re-implemented on top of
MutableMapping abstract base class.
See: commit 2a2cef38feb7f259ea6b5735a6ce3e46812e217d
Fixes: https://github.com/python-ldap/python-ldap/issues/387
=> Add missing cidict.copy() method

Doc/reference/ldapurl.rst, Lib/ldapurl.py, Tests/t_ldapurl.py
Fixes: https://github.com/python-ldap/python-ldap/issues/280
Co-authored-by: David Mulder <dmulder@suse.com>
=> LDAPUrl now treats urlscheme cases insensitive

Doc/reference/ldap-controls.rst, Lib/ldap/controls/readentry.py, Tests/t_ldap_controls_readentry.py
leave them bytes, as it's normal for attribute values.
=> Issue #399: do not decode attribute values of post read control

Doc/conf.py, Doc/reference/ldap-controls.rst, Lib/ldap/controls/ppolicy.py
I just noticed that the `ppolicy` control did not appear in the documentation.
Attributes are auto-documented with [sphinx autoattribute](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute)
> For module data members and class attributes, documentation can either be put into a comment [...] or in **a docstring after the definition**.
=> ppolicy control documentation

Doc/faq.rst
Several posts across the web in regards to this issue, so an additional
note in the answer to this question seems warranted.
Basing this answer on message this message in the mailing list:
https://mail.python.org/pipermail/python-ldap/2014q1/003350.html
Can client code safely assume that a DN of `None` is always a search referral, because that is what I took from the message linked above?
=> Add note to FAQ regarding search referrals

.github/workflows/tox-fedora.yml, Doc/installing.rst, Doc/sample_workflow.rst, Makefile, setup.py, tox.ini
- Add CFLAGS used on Travis CI (`-Werror`, `std=c99` and similar) to tox environments
- Add `std=c90` environments for Python versions that compile with c90
- Add an environment for pypy3 and for Python 3.10 (a bit early, but unlikely to break now)
- Some general clean-up (remove python2 remnants, fix comments)
- Add tox-on-Fedora runs to the CI
Partially addresses: https://github.com/python-ldap/python-ldap/issues/418
~~The actions might not run on the PR that adds them, but they passed here: https://github.com/encukou/python-ldap/actions/runs/983127874~~
=> Clean up tox environments & run tox on Fedora in CI 

Doc/reference/ldap.rst, Lib/ldap/constants.py, Modules/constants_generated.h, Modules/options.c, Tests/t_cext.py
Add bindings for OPT_X_TLS_REQUIRE_SAN option. The flag was introduced
in OpenLDAP 2.4.52 to configure subject alternative name verification.
=> Add OPT_X_TLS_REQUIRE_SAN

LICENCE.MIT, Modules/options.c, Tests/t_ldapobject.py
The options OPT_X_SASL_SSF_MIN, OPT_X_SASL_SSF_MAX, and OPT_X_SASL_SSF
take *ber_len_t as input and output arguments. ber_len_t is defined as
unsigned long:
```
/* LBER lengths (32 bits or larger) */
#define LBER_LEN_T long
typedef unsigned LBER_LEN_T ber_len_t;
```
Wrong type handling is causing issues on big endian platforms.
=> Fix SASL get/set options on big endian platforms

Modules/constants.c
Prevent ``SystemError: error return without exception set`` when LDAP
server returns an unknown LDAP result code.
Fixes: https://github.com/python-ldap/python-ldap/issues/240
=> Handle unknown LDAP result code

Modules/options.c, Tests/t_ldapobject.py
The option flag ``OPT_X_SASL_SSF_EXTERNAL`` never worked because the
set_option code didn't handle the flag correctly.
Fixes: https://github.com/python-ldap/python-ldap/issues/423
=> Implement OPT_X_SASL_SSF_EXTERNAL setter

CHANGES, Doc/installing.rst, Lib/ldap/cidict.py, Lib/ldap/pkginfo.py, Lib/ldapurl.py, Lib/ldif.py, Lib/slapdtest/__init__.py
I would like to release soon. The following fixes might go in before the release: 
After the release:
=> Release 3.4.0

CHANGES, Lib/ldap/schema/tokenizer.py
Fixes: GHSL-2021-117
Thank you to GitHub team members @erik-krogh (Erik Krogh
Kristensen) and @yoff (Rasmus Petersen) for discovering the
issue.
=> Fix inefficient regular expression in the schema tokenizer

Tests/t_cext.py
Introduced in c5ad8025632fb5e5e84cced5a0f8c7ddda1e8dae
These conditions are redundant now, so I assume it’s a mistake.
=> Fix wrong asserts in test_test_flags

Doc/reference/ldap-controls.rst, Doc/reference/ldap-extop.rst
Allow Sphinx to pickup the ASN.1 substitution from pyasn1, so docs can build.
I'm not completely sure that this is how Sphinx is suppose to work though.
=> Add ASN.1 replace to psearch control

Tests/t_ldapobject.py
There appear to be some minor differences in the CPython and Pypy3 implementations of del. 
Use delattr to ensure that hasattr will see the attributes as deleted.
This should fix to of the failing pypy3 test cases.
=> Fix broken reset and tearDown in pypy3

setup.py
Add slapdtest.certs to packages, to fix deprecation warning.
=> Add sldapdtest.certs to setup.py packages

.github/workflows/ci.yml, .github/workflows/tox-fedora.yml, setup.py, tox.ini
Noticed Python 3.10 was missing from GitHub Actions and trove classifiers and 3.11 was missing from those two plus tox.
Stylistic nit: in GHA, quotes are needed around 3.10 in the job matrix because YAML would parse the unquoted version as 3.1, so I went ahead and added quotes around all entries in the `python-version` list for consistency. I can revert this if desired.
=> Add Python 3.10 and 3.11 to CI and tox

.github/workflows/ci.yml, .github/workflows/tox-fedora.yml
Keep 20.04 for py3.6 testing.
Replace deprecated enchant package with enchant-2.
=> Fix CI images after ubuntu-latest update

Doc/conf.py, Doc/faq.rst
Additionally, rename sphinx configuration parameter master_doc to root_doc
Fixes: https://github.com/python-ldap/python-ldap/issues/509
=> Conscious Language: Rename master branch to main branch

SECURITY.md
Closes #529
I've created the SECURITY.md file following a GitHub's template and considering that you'd request that users report vulnerabilities through the [security advisory](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability), which is a handy new GitHub feature, but it's still in beta and **has to be manually enabled by a maintainer**.
If you're interested in this feature, you can activate it following this steps:
1. Click on this [link](https://github.com/python-ldap/python-ldap/settings/security_analysis) to go to Code security & analysis section on your repo's settings
2. Click "Enable" for "Private vulnerability reporting (Beta)"
However, if you'd rather not use this feature, you can also …
=> docs: create Security Policy

Tests/t_ldapobject.py
Per [Python docs](https://docs.python.org/3/library/socket.html#socket.socket.detach) a `socket` object will close the underlying file descriptor on garbage collection and to use it elsewhere, one needs to call `detach()`.
Fixes: https://github.com/python-ldap/python-ldap/issues/460
Closes: https://github.com/python-ldap/python-ldap/pull/543
=> Claim ownership of socket once we've passed it to libldap

Doc/contributing.rst
Current description contains a sentence that miss a negative form, contradicting previous sentence and leaving the reader with an ambiguity.
---
I did not run the tests locally, as 1) the change is in documentation text only 2) this is a fork of current `main` branch, 3) I made the change online, using GitHub editor.
=> docs: add missing negation in contributing.rst

Doc/installing.rst
This PR updates the documentation regarding the build prerequisites. Specifically, it separates build requirements from the ones needed for testing (for Debian).
I tested the build requirements with the following `Dockerfile` and it works.
```
FROM python:3.11
RUN apt-get update \
&& apt-get install -y build-essential ldap-utils \
libldap2-dev libsasl2-dev \
&& rm -rf /var/lib/apt/lists/*
RUN pip install python-ldap==3.4.3
```
=> Update Docs on installation requirements

Lib/ldap/syncrepl.py
Use the name values for result types in syncrepl.py rather than the raw decimal values.
=> Fixes #565 - Use name values instead of raw decimal

.github/workflows/ci.yml, .github/workflows/tox-fedora.yml, setup.py, tox.ini
Update GitHub Actions.
Explicitly install python3-setuptools for Tox env runs on Fedora.
=> Add support for Python 3.13
